name: Nix CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Run flake checks
        run: |
          # This will run all checks defined in your flake
          nix flake check --print-build-logs
      
      - name: Build all packages
        run: |
          nix build .#default --print-build-logs
          nix build .#deb --print-build-logs || echo "Debian build skipped on ${{ matrix.os }}"
      
      - name: Run tests in dev shell
        run: |
          nix develop -c cargo test
          nix develop -c cargo fmt -- --check
          nix develop -c cargo clippy -- -D warnings
      
      - name: Test binary execution
        run: |
          nix run . -- --version